#!/bin/bash
set -eou pipefail
: ${GUIX_BINARY_VERSION:=1.0.1}
: ${DOCKER_CONTAINER_NAME:=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '')}

: ${DOCKERFILE_PATH:=Dockerfile}
: ${IMAGE_NAME:=guix:${GUIX_BINARY_VERSION}}

docker rm -f ${DOCKER_CONTAINER_NAME} 2>/dev/null || true

docker build --build-arg GUIX_BINARY_VERSION=${GUIX_BINARY_VERSION} -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} .

# Create a container with stable release and pull last version
docker run -d --name ${DOCKER_CONTAINER_NAME} --privileged $IMAGE_NAME
docker exec -ti ${DOCKER_CONTAINER_NAME} guix pull
# Restart to have the last version of daemon running
docker restart ${DOCKER_CONTAINER_NAME}
# Delete old generations and clean
docker exec -ti ${DOCKER_CONTAINER_NAME} guix pull --delete-generations
docker exec -ti ${DOCKER_CONTAINER_NAME} guix gc --delete-generations
docker exec -ti ${DOCKER_CONTAINER_NAME} guix gc --optimize
docker exec -ti ${DOCKER_CONTAINER_NAME} guix gc
# Tag new version
docker commit ${DOCKER_CONTAINER_NAME} guix:latest
# Clean
docker rm -f ${DOCKER_CONTAINER_NAME}
